# Generated by Django 4.1.1 on 2022-09-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0002_user_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_date',
            field=models.DateTimeField(),
        ),
    ]
