# Generated by Django 4.1.1 on 2022-09-11 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loging', '0003_user_ad_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ad_id',
            field=models.OneToOneField(default='0000000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
