# Generated by Django 4.1.1 on 2022-09-11 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loging', '0006_alter_user_ad_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='TenentAdmin',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='TenentUser',
        ),
    ]
