# Generated by Django 4.1.1 on 2022-09-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0008_remove_tenentuser_ad_date_remove_tenentuser_ad_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenentAdmin',
        ),
    ]
