# Generated by Django 4.1.1 on 2022-09-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0011_alter_tenentuser_phone1_alter_tenentuser_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenentuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not to say')], default='M', max_length=20),
        ),
    ]
