# Generated by Django 4.1.1 on 2022-09-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0012_alter_tenentuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenentuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='tenentuser',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='tenentuser',
            name='phone2',
        ),
    ]
