# Generated by Django 4.1.1 on 2022-09-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0013_remove_tenentuser_age_remove_tenentuser_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenentuser',
            name='password',
            field=models.CharField(default='adm123', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenentuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not to say')], default='O', max_length=20),
        ),
    ]
