# Generated by Django 4.1.1 on 2022-09-20 13:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0014_tenentuser_password_alter_tenentuser_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tenentuser',
            managers=[
                ('emp_auth', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tenentuser',
            name='password',
            field=models.CharField(default='adm123', max_length=100),
        ),
    ]
