# Generated by Django 4.1.1 on 2022-09-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loging', '0015_alter_tenentuser_managers_alter_tenentuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('price', models.IntegerField()),
                ('BHK', models.CharField(choices=[('unknown', 'unknown'), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK')], default='unknown', max_length=7)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unknown', 'unknown'), ('Ready to move', 'Ready To Move'), ('Under Construction', 'Under Construction'), ('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], default='unknown', max_length=20)),
                ('prop_type', models.CharField(choices=[('Type Unknown', 'Type Unknown'), ('Flat', 'Flat'), ('House', 'House'), ('Shop', 'Shop'), ('Warehouse', 'Warehouse'), ('Land(Plot)', 'Land(Plot)')], default='Type Unknown', max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('for_sell_or_rent', models.CharField(choices=[('unknown', 'unknown'), ('SELL', 'SELL'), ('BUY', 'BUY'), ('RENT', 'RENT')], default='unknown', max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('prop_number', models.CharField(max_length=30)),
                ('user_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loging.tenentuser')),
            ],
        ),
    ]
