# Generated by Django 4.1.1 on 2022-09-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='User_Images/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
